; to count how many number of 0 and 1 present in the give 8 bit number

LDA 8000H   ; 8 BIT DATA
MVI B, 08H ; 8 BIT COUNTER
MVI C, 00H ; TO COUNT ONLY ZERO

BACK: RRC
JC ONE
INR C
ONE: DCR B
JNZ BACK
MOV A, C
STA 8500H   ;TO STORE TOTAL NUMBER OF ZERO COUNTED
MVI A, 08H 
SUB C
STA 8501H  ; STORE TOAL NO. OF 1 COUNTER AFTER SUBTRACTING FROM TOTAL BIT
HLT
